onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/client'
  - better-sqlite3
  - bufferutil
  - core-js
  - core-js-pure
  - es5-ext
  - gatsby
  - gatsby-cli
  - lmdb
  - msgpackr-extract
  - sharp
  - sqlite3
